language: java
jdk:
  - openjdk11

branches:
  only:
    - master
    - develop
    # Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - nutee.skhu.2020@gmail.com
      - mf311110@gmail.com

before_install:
  - chmod +x gradlew
