version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/NUTEE/back/
    overwrite: yes

hooks:
  ApplicationStart: # 배포가 끝나면 아래 명령어를 실행
    - location: /home/ec2-user/NUTEE/back/execute-deploy.sh
      timeout: 180
