server.port: 9425
my.upload.path: C:\\image\\
jwt.secret: nutee
aws.bucket: nuteestorage

#MYSQL CONFIG
spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/nutee_test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: P@ssw0rd
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

cloud:
  aws:
    region:
      static: ap-northeast-2
    credentials:
      access-key: AKIATMO3KHNJRJJHGLTE
      secret-key: 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
